"""pk_changes

Revision ID: 0a0e2bec36c6
Revises: 0a9424eea157
Create Date: 2024-05-10 15:46:54.988447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0e2bec36c6'
down_revision: Union[str, None] = '0a9424eea157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_name_of_product', table_name='product')
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.create_index('ix_product_name_of_product', 'product', ['name'], unique=False)
    # ### end Alembic commands ###
