"""some changes

Revision ID: 0a9424eea157
Revises: 4f77ec297c1d
Create Date: 2024-04-22 15:03:35.924539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9424eea157'
down_revision: Union[str, None] = '4f77ec297c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dish_type_of_dish_id_fkey', 'dish', type_='foreignkey')
    op.create_foreign_key(None, 'dish', 'type_of_dish', ['type_of_dish_id'], ['id'])
    op.add_column('unit_of_measurement', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_index('ix_unit_of_measurement_name_unit_of_measurement', table_name='unit_of_measurement')
    op.create_index(op.f('ix_unit_of_measurement_name'), 'unit_of_measurement', ['name'], unique=False)
    op.drop_column('unit_of_measurement', 'name_unit_of_measurement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_of_measurement', sa.Column('name_unit_of_measurement', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_unit_of_measurement_name'), table_name='unit_of_measurement')
    op.create_index('ix_unit_of_measurement_name_unit_of_measurement', 'unit_of_measurement', ['name_unit_of_measurement'], unique=False)
    op.drop_column('unit_of_measurement', 'name')
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.create_foreign_key('dish_type_of_dish_id_fkey', 'dish', 'type_of_product', ['type_of_dish_id'], ['id'])
    # ### end Alembic commands ###
